version: '3.1'

services:
  database:
    container_name: postgres_dev
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: hmanager
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: