spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmanager-test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: local_user
    password: local_password


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    clean-disabled: false


axon:
  axonserver:
    enabled: false
auth:
  keystore:
    jks-location: classpath:/keystore/hmanager.jks
    pass: asdf123
    key-alias: hmanager_jwt
logging:
  level:
    web: info