spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmanager?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: local_user
    password: local_password

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    clean-disabled: false

axon:
  axonserver:
    enabled: false