spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hmanager?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: local_user
    password: local_password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  error:
    include-stacktrace: never

auth:
  keystore:
    jks-location: classpath:/keystore/hmanager.jks
    pass: asdf123
    key-alias: hmanager_jwt
logging:
  level:
    web: info
    org:
      springframework:
        web: info
        security: info
