spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DATABASE_USER_NAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  error:
    include-stacktrace: never

axon:
  axonserver:
    enabled: false
auth:
  keystore:
    jks-location: classpath:/keystore/hmanager.jks
    pass: asdf123
    key-alias: hmanager_jwt

